### ISSUE TITLE
Issue with the Basic Usage Example

### ISSUE THREAD

**Issue by angry-dad** [JerrettDavis/MyQDotNet#1]
Thanks for making this library. I am porting my Python app on my Raspberry Pi into a .NET Core worker service thanks to this library. I ran into issues with the example you have under "Basic Usage".  I believe the LINQ statement should be:

`var garageDoor = api.Devices.Values.Where(d => d.DeviceFamily == "garagedoor")`

api.Values returns the KV pair, which does not have the DeviceFamily property and cannot be cast on the following line. 
After that change everything worked fine.

**Comment by JerrettDavis** [comment]
Ah, good catch. It looks like I did overlook that.
