### ISSUE TITLE
[Question] What and when the DoorState.Transition and DoorState.Stopped states are and when they could occur?

### ISSUE THREAD

**Issue by arivera12** [JerrettDavis/MyQDotNet#3]

**Comment by JerrettDavis** [comment]
I actually snagged those from the [arraylabs/pymyq](https://github.com/arraylabs/pymyq) python MyQ wrapper. I'm not certain when they can occur, but I believe stopped is when the door has been manually stopped via the garage door opener, and transition occurs directly between stage changes.

**Comment by arivera12** [comment]
Ok. Thanks for the info!
